from __future__ import annotations

import base64
import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

# Build-time managed keys. These are generated by tools/inject_managed_keys.py
# during a private Windows build. Source-ready packages intentionally leave them blank.
MANAGED_KEYS_B64 = "eyJvcGVuYWlwX2tleSI6ImYwN2ZkOTcwYmMyZGZmMWY2MTU5MGU4ZmZmODU0NjZmIiwibGlkb19zdWJzY3JpcHRpb25fa2V5IjoiMThiOGUyMzkwZjJmNDg0MWJhZjQ1Mzk0NDQxNWRiODkiLCJsaWRvX2xpYnJhcnlfY29kZSI6IldXRiIsImxpZG9fcmV2aXNpb25fd2VlayI6IjI2MDYifQ=="

PRIVATE_KEY_PATH_ENV = "OPSROOM_PRIVATE_KEYS_FILE"
DEFAULT_PRIVATE_KEY_PATH = r"E:\Ops Room Project\private_keys\opsroom_api_keys.local.json"


def _safe_text(value: Any) -> str:
    if value is None or isinstance(value, (dict, list)):
        return ""
    return str(value).strip()


def _load_json_file(path: Path) -> dict[str, Any]:
    try:
        if path.is_file():
            data = json.loads(path.read_text(encoding="utf-8"))
            return data if isinstance(data, dict) else {}
    except Exception:
        return {}
    return {}


@lru_cache(maxsize=1)
def managed_keys() -> dict[str, Any]:
    data: dict[str, Any] = {}
    if MANAGED_KEYS_B64:
        try:
            raw = base64.b64decode(MANAGED_KEYS_B64.encode("ascii"), validate=True).decode("utf-8", errors="ignore")
            loaded = json.loads(raw)
            if isinstance(loaded, dict):
                data.update(loaded)
        except Exception:
            pass
    # Runtime local override for private validation. This file is never copied into dist.
    local_path = _safe_text(os.getenv(PRIVATE_KEY_PATH_ENV)) or DEFAULT_PRIVATE_KEY_PATH
    data.update(_load_json_file(Path(local_path)))
    return data


def get_secret(*names: str, env: str = "") -> str:
    if env:
        value = _safe_text(os.getenv(env))
        if value:
            return value
    keys = managed_keys()
    for name in names:
        value = _safe_text(keys.get(name))
        if value:
            return value
    return ""


def redacted(value: str) -> str:
    value = _safe_text(value)
    if len(value) <= 8:
        return "configured" if value else "not configured"
    return f"{value[:3]}…{value[-3:]}"
